import type { Metadata } from "next";
import { Inter, Montserrat_Alternates } from "next/font/google";
import "./globals.css";


const montserratAlternates = Montserrat_Alternates({
  variable: '--font-montserrat-alt',
  subsets: ['cyrillic', "latin"],
  display: 'swap',
  weight: ['600']
});

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratAlternates.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
